<?php
include_once('single-image/shortcode_composer.php');
include_once('title-text/shortcode_composer.php');
include_once('frontbox/shortcode_composer.php');
include_once('latest-posts/shortcode_composer.php');
include_once('shop-now/shortcode_composer.php');
include_once('single-button/shortcode_composer.php');
include_once('question-answer/shortcode_composer.php');
?>